# Generated by Django 2.0.2 on 2018-03-28 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulz',
            name='city',
            field=models.CharField(default='Paris', max_length=255),
        ),
        migrations.AddField(
            model_name='rulz',
            name='complexity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rulz',
            name='country',
            field=models.CharField(default='France', max_length=255),
        ),
        migrations.AddField(
            model_name='rulz',
            name='player_num',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='rulz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
