# Generated by Django 2.0.2 on 2018-03-28 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulz', '0002_auto_20180327_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulz',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
