# Generated by Django 2.0.2 on 2018-04-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulz', '0005_auto_20180430_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulzcomment',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcomments', to='rulz.Rulz'),
        ),
    ]
