# Generated by Django 2.0.2 on 2018-05-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180510_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='user',
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
