# Generated by Django 2.0.2 on 2018-05-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180415_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='league_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='league_subleader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='league',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='home.League'),
        ),
    ]
